### ISSUE TITLE
一些功能建议

### ISSUE THREAD

**Issue by FZDSLR** [ekoooo/Ximalaya-Cascades#1]
- 可添加收藏专辑或主播，并将其显示在左侧栏的一个子条目下 的功能
- 播放页高亮条目颜色可进行调整
![IMG_20201127_230332](https://user-images.githubusercontent.com/62922415/100462373-25943700-3105-11eb-9df9-08094ef29b99.png)
![IMG_20201127_230343](https://user-images.githubusercontent.com/62922415/100462381-2927be00-3105-11eb-94fb-33ec23fba627.png)
（以上为使用光学摇杆操作的画面）
- 可添加节目下载功能

**Comment by ekoooo** [comment]
@FZDSLR 目前 BB10 用户很少，使用者寥寥无几，暂时没有继续修改或新增功能的计划，黑莓真机 debug 签名服务也停止了，开发也很不方便😩

**Comment by FZDSLR** [comment]
好的。

发送自我的 BlackBerry 10 智能手机。
发件人： ekoooo
已发送： 2020年11月30日星期一 10:48
收件人： ekoooo/Ximalaya-Cascades
答复： ekoooo/Ximalaya-Cascades
抄送： FZDSLR; Mention
主题： Re: [ekoooo/Ximalaya-Cascades] 一些功能建议 (#1)


@FZDSLR<https://github.com/FZDSLR> 目前 BB10 用户很少，使用者寥寥无几，暂时没有继续修改或新增功能的计划，黑莓真机 debug 签名服务也停止了，开发也很不方便😩
